### ISSUE TITLE
Syntax Docs typo

### ISSUE THREAD

**Issue by ShaneBeee** [OfficialDonut/SkVault#2]
Hey small typo in the docs

```
on vault withdraw request:
    remove event-number to {balances::%player%}
```

Ive used this in my skript and it runs and error.... if i change the "TO" to "FROM" it works totally fine.

**Comment by OfficialDonut** [comment]
Oops thanks

**Comment by ShaneBeee** [comment]
You're welcome.
When I first saw it I ASSUMED it would be from, and sure enough it was :)
